//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdjwebapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class RoomSong : BaseModel
    {
        public RoomSong()
        {
            Init();
        }

        public RoomSong(StatusCode code) : base(code)
        {
            Init();
        }

        void Init()
        {
            Rooms = new HashSet<Room>();
        }
    
        public int SongId { get; set; }
        public int RoomId { get; set; }
        public string SourceId { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        public string Thumbnail { get; set; }
        public string Thumbnail_Lg { get; set; }
        public int? Length { get; set; }
        public DateTime? PublishedDate { get; set; }
        public int Tokens { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string Source { get; set; }
        public int? SourceLikeCount { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual Room Room { get; set; }
    }
}
