//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace cdjwebapi.Models
{
    public class Room : BaseModel
    {
    	public Room()
    	{
    		Init();
    	}
    	
    	public Room(CDJStatusCode code) : base(code)
    	{
    		Init();
    	}
    
    	public Room(Status status) : base(status)
    	{
    		Init();
    	}
    
        private void Init()
        {
            RoomSongs = new HashSet<RoomSong>();
            RoomUsers = new HashSet<RoomUser>();
        }
    
        public int RoomId { get; set; }
        public int? HostId { get; set; }
        public string RoomName { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public bool isPrivate { get; set; }
        public int? AccessCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int? CurrentSongId { get; set; }
        public string BannerUrl { get; set; }
        public int? CurrentSongTime { get; set; }
        public bool? IsPlaying { get; set; }
        public bool? AllowYT { get; set; }
        public bool? AllowSP { get; set; }
    
        public virtual User Host { get; set; }
        public virtual RoomSong CurrentSong { get; set; }
        public virtual ICollection<RoomSong> RoomSongs { get; set; }
        public virtual ICollection<RoomUser> RoomUsers { get; set; }
    }
}
