//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdjwebapi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class User : BaseModel
    {
        public User()
        {
            Init();
        }

        public User(StatusCode code) : base(code)
        {
            Init();
        }

        private void Init()
        {
            Rooms = new HashSet<Room>();
            RoomUsers = new HashSet<RoomUser>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public DateTime CreatedDate { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ImageUrl { get; set; }
        public string spUsername { get; set; }
        public string spCanonicalUsername { get; set; }
        public string spEmail { get; set; }
        public bool? spProduct { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Room> Rooms { get; set; }
        [JsonIgnore]
        public virtual ICollection<RoomUser> RoomUsers { get; set; }
    }
}
